### ISSUE TITLE
Custom Query

### ISSUE THREAD

**Issue by rajkumarpb** [nacasha/CIgniter-Datatables#8]
Thanks for the awesome work and sharing it! 

I would like to know if it is possible to use the custom query in this data tables? If yes, can you please let me know how can we do it?

**Comment by nacasha** [comment]
I'm afraid it's not possible because the library I used in this Package is using [Query Builder Class](https://www.codeigniter.com/userguide3/database/query_builder.html) from Code Igniter with some adjustments.

That means you can only use methods from Query Builder Class. (except methods that starts with 'get')
